### ISSUE TITLE
sub-container assignment

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/url#77]
e.g. `u1.params() = u2.params()`

We might be able to do segments generically.

**Comment by vinniefalco** [comment]
Does this already work?

**Comment by alandefreitas** [comment]
Let me check

**Comment by alandefreitas** [comment]
It doesn't work yet :(

**Comment by alandefreitas** [comment]
No custom `operator=` is defined and `assign(other.begin(), other.end())` doesn't work because `*other.begin()` is a different type.

The default `operator=` will just copy the underlying pointer to the URL, which I think is expected behavior?

We can't delete `operator=` because `params` is a reference-like type. So this is going to be the final behavior.

**Comment by vinniefalco** [comment]
can we put `&` or `&&` on `operator=` to prevent this from compiling:
```
u1.params() = u2.params();
```

But still allow this to compile:
```
auto p = u1.params();
p = u2.params();
```
?

**Comment by alandefreitas** [comment]
A single `&` works: https://godbolt.org/z/xxbbEMMx1
